### ISSUE TITLE
/tp bottomline.teleport needs removing.

### ISSUE THREAD

**Issue by NTR-9000** [Banjo-226/bottom-line#12]
This overwrites the default teleport command and doesnt allow teleporting entities etc.
It also interferes with commands blocks when teleporting 

> "@a[r=1,x=*,y=*,z=*]"

 to coordinates.
please add a feature to disable the bottomline tp command and reenable the original minecraft one.

**Comment by Banjo-226** [comment]
You can still use the default one :) Try using /bukkit:tp
