### ISSUE TITLE
Inventory, kits and wishlist

### ISSUE THREAD

**Issue by glob03** [Banjo-226/bottom-line#2]
Hi, when the default user does /inv the GUI gives them access to creative mode? maybe i have my permissions wrong?

I don't seem to be able to give default access to kits without ...kit.*
the block seems to be from outside bottomline?

any chance of moving motd and rules and other formatted strings to a text file?

spigot 1.8.9 java8 vault, EssentialGroupmanager & Linux

**Comment by Banjo-226** [comment]
The inventory showing the players inventory should only change the desired players inventory. I will make it so the player has to have the permission to change the other players inventory. And, I'll see what's wrong with the game mode changer.

Make sure the players have bottomline.kit and bottomline.kit.[case sensitive kit name here]

I could try move the MOTD and rules to a text file

Tell me if this resolved your problems.

**Comment by glob03** [comment]
Thanks Banjo

On 22-12-2015 10:19, Banjo wrote:

> The inventory showing the players inventory should only change the
> desired players inventory. I will make it so the player has to have
> the permission to change the other players inventory.
> 
> And, I'll see
> what's wrong with the game mode changer.

I don't think anything is up, except they have access to creative mode
from their /inv, however they don't have any access via commands.

> Make sure the players have bottomline.kit and bottomline.kit.[case
> sensitive kit name here]

yes i think this worked for me a couple of days ago, but it doesnt
seem to be enough anymore?????

I will look again later today

> I could try move the MOTD and rules to a text file

Thanks this would help saving re-configuring the setup
on an upgrade.

That and the ability to just not display the motd, were
2 options of EssentialsX I particularly liked. However
the command /motd still worked in the game.

but it's not a biggy, eh :)

cheers

> Tell me if this resolved your problems.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/Banjo-226/bottom-line/issues/2#issuecomment-166455727

  Regards

##   Greg

  -[ Registered Linux User #159346 ]-
  http://baratel.com.au/

This Email may contain privileged information and
remains the property of the author. You may not
reveal the contents to anyone without the authors
express authority

Why people with a social conscience don't use apple:-
https://en.wikipedia.org/wiki/Criticism_of_Apple_Inc.
http://www.forbes.com/sites/petercohan/2012/01/26/23-died-building-your-iworld-time-to-boycott-apple/

Why I wouldn't use Microsoft either
https://en.wikipedia.org/wiki/Criticism_of_Microsoft

Operating System Popularity
https://en.wikipedia.org/wiki/Usage_share_of_operating_systems

Open Source
https://en.wikipedia.org/wiki/Open-source_software
http://www.gnu.org/philosophy/free-software-for-freedom.en.html

**Comment by glob03** [comment]
Hi, according to GroupManager the default group has those
attributes, as does a user in this group. The commands
/kit /showkit <kitname> both work as expected, but /kit <kitname>
results in"
Insufficient permissions to use that kit! in light red

The only odd thing i see in the log is this
[13:31:00] [Server thread/WARN]: [BottomLine] Default system encoding 
may have misread config.yml from plugin jar
[13:31:00] [Server thread/INFO]: [BottomLine] Enabled configuration!

Extra logging from GroupManager is unenlightening, I noticed multiverse
spits out the missing permissions sometimes, and I realise this all
adds to bloat, if others haven't experienced this problem, it may be
something peculiar to my set up (still in the fiddling stage), I've
managed to get around it by using kits.\* then negating the commands I
don't want the default user to have.

cheers

On 22-12-2015 10:19, Banjo wrote:

> The inventory showing the players inventory should only change the
> desired players inventory. I will make it so the player has to have
> the permission to change the other players inventory. And, I'll see
> what's wrong with the game mode changer.
> 
> Make sure the players have bottomline.kit and bottomline.kit.[case
> sensitive kit name here]
> 
> I could try move the MOTD and rules to a text file
> 
> Tell me if this resolved your problems.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/Banjo-226/bottom-line/issues/2#issuecomment-166455727

  Regards

##   Greg

  -[ Registered Linux User #159346 ]-
  http://baratel.com.au/

This Email may contain privileged information and
remains the property of the author. You may not
reveal the contents to anyone without the authors
express authority

Why people with a social conscience don't use apple:-
https://en.wikipedia.org/wiki/Criticism_of_Apple_Inc.
http://www.forbes.com/sites/petercohan/2012/01/26/23-died-building-your-iworld-time-to-boycott-apple/

Why I wouldn't use Microsoft either
https://en.wikipedia.org/wiki/Criticism_of_Microsoft

Operating System Popularity
https://en.wikipedia.org/wiki/Usage_share_of_operating_systems

Open Source
https://en.wikipedia.org/wiki/Open-source_software
http://www.gnu.org/philosophy/free-software-for-freedom.en.html

**Comment by Banjo-226** [comment]
Thanks for giving these suggestions a try!

I have not tried this plugin with Multiverse before and it seems like you'll have to do what you're doing right now.

I have not heard of anyone else having the same issues as you, but hopefully you'll be able to get them fixed. If there is a stack trace or error please tell me immediately and I'll try fix it

Thanks, when you've fixed this issue and no longer require assistance please close the issue.

**Comment by Banjo-226** [comment]
Updated and should have fixed issue.
MOTD and rules have been moved to own file

Added a few commands too: [see here](https://www.spigotmc.org/resources/bottomline.15348/update?update=59698)

Closing this issue, email me at banjotehcat@gmail.com if you have any more issues :)

**Comment by glob03** [comment]
Hi Banjo, sorry for bothering you, but I think I'm
missing something with the economy, the total doesn't
seem to be updating from the users pocket? and I don't
appear to be able to transfer these credits to a bank?

do you have recommended plugins for these tasks?

Using:
Economy Bank 1.3.1
[1.7.10 - 1.8.9] MySQL or FlatFile Economy Bank System using signs.

and vault

Thanks for the external motd, however when i change it, it
gets overwritten by the default :) (i've got around this by
changing the write permissions on the file.

other than the balance appearing to reset itself upon a reboot,
and the file not keeping in sync with what's in memory, the
persistent motd, and burn seems pretty brief (less than 1 sec.)
everything seems fine?, I've been experiencing some issues with
chat, but not sure where that's coming from at the moment.

cheers

**Comment by Banjo-226** [comment]
You won't need another economy plugin. Unfortunately, as of this current time you will have to manually transfer all of the balances from your current economy plugin, to this plugin. Once you do that, you can remove the current economy plugin which is Economy Bank by the looks.
