### ISSUE TITLE
bottomline.fly and bottomline.fly* not working with zpermissions

### ISSUE THREAD

**Issue by BattleFox2** [Banjo-226/bottom-line#7]
Hello i downloaded you plugin and i really enjoy it. thanks for that.
The problem that comes up, is that when i give a user the permission bottomline.fly nothing happens when typing fly. When i am typing /fly in op it works fine. Other permissions like bottomline.heal or bottomline.feed work perfectly fine and i have no erros.
please fix it or tell me how to, thanks.

Greetings Paul

**Comment by Banjo-226** [comment]
Hi mate,

Sorry for this inconvenience. Will be fixed in the update (being released shortly)
